<a href="https://colab.research.google.com/github/yashchoudhery/Python-For-Learning/blob/main/Python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Split Concatinate


#Importing numpy library

In [ ]:
import numpy as np


##Making an Numpy array using a-range(arange)


In [ ]:
 ar=np.arange(10)
 ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Generating random permutation of an array

In [ ]:
a=np.random.permutation(np.arange(5))
b=np.random.permutation(np.arange(5))
print(a)
print(b)

[2 1 3 4 0]
[2 1 4 0 3]


In [ ]:
np.concatenate([a,b,a])##Here we can pass N no of array

array([3, 4, 0, 1, 2, 2, 4, 3, 1, 0, 3, 4, 0, 1, 2])

##Checked for 2D and 3D

In [ ]:
a=np.array([
            [1,2,3],
            [4,5,6]

])

In [ ]:
b=np.array([
            [7,8,9],
            [10,11,12]

])

In [ ]:
np.concatenate([a,b])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Note-> If the sizes is not uniform the it will show error


#by this we can able to concatinate 2 2D array with un consistent sizes in a horizontal way

In [ ]:
a=np.array([
            [1,2],
            [4,5]

])
b=np.array([
            [7,8,9],
            [10,11,12]

])


In [ ]:
np.hstack([a,b])

array([[ 1,  2,  7,  8,  9],
       [ 4,  5, 10, 11, 12]])

##By this we can continate in Vertical 2D Array

In [ ]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**this is only done when a and b bth 2D array are of same row and coloumn otherwise it will show error**

**there is one more stack which extent in 3 dimentional  that is np.Dstack([name of arrays ])   
** Here in the below

In [ ]:
np.dstack([a,b])

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.dstack([a,b])

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [ ]:
np.dstack([a,b]).shape## it will give the dimention of the array

(1, 4, 2)

In [ ]:
a=np.array([
            [1,2,3],
            [4,5,6]

])
b=np.array([
            [7,8,9],
            [10,11,12]

])

In [ ]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([a,b],axis=1)##this is same as h stack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.concatenate([a,b],axis=0)##while axis is zero then it is same as vstack

**the use of axis is only on 2D array** 

In [ ]:
ar=np.array([1,2,3,4])
np.append(ar,8)

array([1, 2, 3, 4, 8])

In [ ]:
ar


array([1, 2, 3, 4])

by this we get that the above one in the append function 8 will be added in anew array else
ar havent getv any changes

In [ ]:
np.append(ar,([1,2,7,7]))

array([1, 2, 3, 4, 1, 2, 7, 7])

In [ ]:
np.append(ar,np.array([1,2,7,7]))

array([1, 2, 3, 4, 1, 2, 7, 7])

we can also append the list or a  new array and form a new array

In [ ]:
#Max dimention array can be

##Max dimention array can be formed is 32 D

In [ ]:
l=[1]*32

t=tuple(l)


In [ ]:
np.ones(l)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1.]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

the above is the 32 dimention array

In [ ]:
np.ones(l).shape

(1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1)

#split

In [ ]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(ar,[4,7,9,1])

[array([0, 1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([], dtype=int64),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [ ]:
ar[2:5]##range use


array([2, 3, 4])

In [ ]:
print(ar[0:])


[0 1 2 3 4 5 6 7 8 9]
